### PR TITLE
Add eu-west-2 bucket mapping

### PR DESCRIPTION
**Pull request by dougneal**
Add bucket mapping for the eu-west-2 region.

Of course the bucket will also need to be created and populated.

### CODE REVIEW

**Comment by mrcoronel** [comment]
Hi @dougneal, I'm afraid I can't accept this request as I can't create the bucket for eu-west-2. It seems someone has already taken it

**Comment by dougneal** [comment]
That's pretty annoying! And whoever has selfishly taken that bucket name (presumably to do the same thing I'm trying to do) won't even benefit from having its contents maintained upstream 😞 

I've updated the PR to map eu-west-2 to the eu-west-1 bucket - would that be acceptable?

**Comment by mrcoronel** [comment]
I've created snapshots-tool-aurora-eu-west-2-real (sorry, it's the best I could come up with)
Pointing to the bucket in eu-west-1 will not work unfortunately. The code needs to be in the same region where the Lambda functions are being deployed

**Comment by dougneal** [comment]
Oh cool, thanks. I'll update the PR now.

**Pull request merged**
